services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_ACCESS_KEY_VALUE=${AWS_ACCESS_KEY_VALUE}
    env_file:
      - .env
    restart: always
      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443" # Si decides habilitar HTTPS más adelante
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always