services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443" # Si decides habilitar HTTPS más adelante
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Monta tu archivo de configuración aquí
    depends_on:
      - fastapi
    restart: always
